account: UA-72957768-1
cross_domains: ''
codesnippet:
  create: {  }
  before: ''
  after: ''
custom:
  dimension: {  }
  metric: {  }
domain_mode: 0
track:
  files: false
  files_extensions: ''
  colorbox: false
  linkid: false
  userid: false
  mailto: false
  messages: {  }
  outbound: false
  site_search: false
  adsense: false
  displayfeatures: false
privacy:
  anonymizeip: true
cache: false
debug: false
visibility:
  request_path_mode: 0
  request_path_pages: /user
  user_role_mode: null
  user_role_roles: {  }
  user_account_mode: 0
